"""
NutriOS — Pydantic Schemas

All request/response models for the API. Every route uses these
for input validation, serialization, and OpenAPI doc generation.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ═══════════════════════════════════════════════════════════════
# ENUMS
# ═══════════════════════════════════════════════════════════════

class MealType(str, Enum):
    """Meal category enum."""
    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"
    SNACK = "snack"


class GoalType(str, Enum):
    """User dietary goal."""
    LOSE_WEIGHT = "lose_weight"
    GAIN_MUSCLE = "gain_muscle"
    MAINTAIN = "maintain"
    EAT_HEALTHIER = "eat_healthier"


# ═══════════════════════════════════════════════════════════════
# COMMON
# ═══════════════════════════════════════════════════════════════

class Macros(BaseModel):
    """Macronutrient breakdown."""
    calories: float = Field(..., ge=0, description="Total calories (kcal)")
    protein_g: float = Field(..., ge=0, description="Protein in grams")
    carbs_g: float = Field(..., ge=0, description="Carbohydrates in grams")
    fat_g: float = Field(..., ge=0, description="Fat in grams")
    fiber_g: Optional[float] = Field(None, ge=0, description="Fiber in grams")


class NearbyPlace(BaseModel):
    """A nearby food establishment."""
    name: str = Field(..., description="Restaurant/place name")
    address: str = Field(default="", description="Formatted address")
    distance_meters: Optional[float] = Field(None, description="Distance from user in meters")
    rating: Optional[float] = Field(None, ge=0, le=5, description="Google rating")
    place_id: Optional[str] = Field(None, description="Google Place ID")


class CalendarEvent(BaseModel):
    """An upcoming calendar event."""
    summary: str = Field(..., description="Event title")
    start_time: str = Field(..., description="Event start time (ISO 8601)")
    end_time: Optional[str] = Field(None, description="Event end time (ISO 8601)")
    minutes_until: Optional[int] = Field(None, description="Minutes until this event starts")


# ═══════════════════════════════════════════════════════════════
# USER PROFILE
# ═══════════════════════════════════════════════════════════════

class UserProfile(BaseModel):
    """User profile with dietary goals and preferences."""
    user_id: str = Field(..., description="Unique user identifier")
    name: str = Field(..., description="User's display name")
    goal: GoalType = Field(default=GoalType.EAT_HEALTHIER, description="Primary dietary goal")
    dietary_restrictions: List[str] = Field(
        default_factory=list,
        description="List of dietary restrictions (e.g., vegetarian, gluten-free)",
    )
    daily_calorie_target: Optional[int] = Field(
        None, ge=800, le=10000, description="Daily calorie target"
    )
    timezone: str = Field(default="UTC", description="User's timezone")
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class UserProfileUpdate(BaseModel):
    """Fields that can be updated on a user profile."""
    name: Optional[str] = None
    goal: Optional[GoalType] = None
    dietary_restrictions: Optional[List[str]] = None
    daily_calorie_target: Optional[int] = Field(None, ge=800, le=10000)
    timezone: Optional[str] = None


# ═══════════════════════════════════════════════════════════════
# NUDGE
# ═══════════════════════════════════════════════════════════════

class NudgeRequest(BaseModel):
    """Request body for the contextual nudge endpoint."""
    latitude: float = Field(..., ge=-90, le=90, description="User's current latitude")
    longitude: float = Field(..., ge=-180, le=180, description="User's current longitude")
    activity_level: Optional[str] = Field(
        None,
        description="Self-reported activity level today (sedentary, light, moderate, active)",
    )


class NudgeResponse(BaseModel):
    """Contextual food nudge generated by Gemini."""
    nudge: str = Field(..., description="The personalized food recommendation")
    nearby_places: List[NearbyPlace] = Field(
        default_factory=list, description="Relevant nearby food options"
    )
    next_event: Optional[CalendarEvent] = Field(
        None, description="User's next scheduled event"
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Timestamp of generation",
    )
    message: str = Field(
        default="Here's your personalized food nudge!",
        description="Human-readable status message",
    )


# ═══════════════════════════════════════════════════════════════
# FOOD LOGGING
# ═══════════════════════════════════════════════════════════════

class MealLogEntry(BaseModel):
    """A single logged meal."""
    meal_id: Optional[str] = None
    food_name: str = Field(..., description="Identified food name")
    description: Optional[str] = Field(None, description="Additional description")
    meal_type: MealType = Field(..., description="Type of meal")
    macros: Macros = Field(..., description="Estimated macronutrient breakdown")
    logged_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Timestamp when meal was logged",
    )
    source: str = Field(
        default="manual",
        description="How the meal was logged (photo or manual)",
    )
    confidence: Optional[float] = Field(
        None, ge=0, le=1, description="AI confidence score for photo-based logs"
    )


class ManualLogRequest(BaseModel):
    """Request to manually log a meal."""
    food_description: str = Field(
        ..., min_length=2, max_length=500,
        description="Text description of what was eaten",
    )
    meal_type: MealType = Field(..., description="Type of meal")


class PhotoLogResponse(BaseModel):
    """Response from photo-based food logging."""
    meal: MealLogEntry = Field(..., description="The identified and logged meal")
    message: str = Field(
        default="Meal identified and logged successfully!",
        description="Human-readable status message",
    )


class ManualLogResponse(BaseModel):
    """Response from manual food logging."""
    meal: MealLogEntry = Field(..., description="The analyzed and logged meal")
    message: str = Field(
        default="Meal logged successfully!",
        description="Human-readable status message",
    )


# ═══════════════════════════════════════════════════════════════
# CHAT COACH
# ═══════════════════════════════════════════════════════════════

class ChatMessage(BaseModel):
    """A single message in the conversation."""
    role: str = Field(..., description="Message role: 'user' or 'assistant'")
    content: str = Field(..., description="Message content")


class CoachRequest(BaseModel):
    """Request to the food coaching chat endpoint."""
    message: str = Field(
        ..., min_length=1, max_length=2000,
        description="User's message to the coach",
    )
    conversation_history: List[ChatMessage] = Field(
        default_factory=list,
        description="Previous messages in this conversation (for multi-turn context)",
    )


class CoachResponse(BaseModel):
    """Response from the food coaching chat."""
    reply: str = Field(..., description="Coach's response")
    message: str = Field(
        default="Coach response generated.",
        description="Human-readable status message",
    )


# ═══════════════════════════════════════════════════════════════
# WEEKLY REPORT
# ═══════════════════════════════════════════════════════════════

class DailyBreakdown(BaseModel):
    """Nutrition summary for a single day."""
    date: str = Field(..., description="Date (YYYY-MM-DD)")
    total_calories: float = Field(default=0, ge=0)
    total_protein_g: float = Field(default=0, ge=0)
    total_carbs_g: float = Field(default=0, ge=0)
    total_fat_g: float = Field(default=0, ge=0)
    meal_count: int = Field(default=0, ge=0)


class HabitScore(BaseModel):
    """Behavioral habit scoring — rewards consistency, variety, and timing."""
    overall_score: float = Field(..., ge=0, le=100, description="Overall habit score (0-100)")
    consistency_score: float = Field(..., ge=0, le=100, description="Meal timing consistency")
    variety_score: float = Field(..., ge=0, le=100, description="Food variety diversity")
    timing_score: float = Field(..., ge=0, le=100, description="Eating at regular times")
    streak_days: int = Field(default=0, ge=0, description="Current logging streak in days")


class WeeklyReport(BaseModel):
    """Weekly nutrition and habit report."""
    user_id: str
    period_start: str = Field(..., description="Report period start (YYYY-MM-DD)")
    period_end: str = Field(..., description="Report period end (YYYY-MM-DD)")
    daily_breakdown: List[DailyBreakdown] = Field(default_factory=list)
    average_daily_calories: float = Field(default=0, ge=0)
    habit_score: HabitScore
    insights: List[str] = Field(
        default_factory=list,
        description="AI-generated insights about the user's week",
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat()
    )
    message: str = Field(
        default="Your weekly report is ready!",
        description="Human-readable status message",
    )


# ═══════════════════════════════════════════════════════════════
# GENERIC RESPONSES
# ═══════════════════════════════════════════════════════════════

class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(default="healthy", description="Service health status")
    service: str = Field(default="nutrios", description="Service name")
    version: str = Field(default="1.0.0", description="API version")
    environment: str = Field(default="development", description="Runtime environment")


class ErrorResponse(BaseModel):
    """Standardized error response."""
    error: str = Field(..., description="Error type")
    message: str = Field(..., description="Human-readable error description")
    detail: Optional[Dict[str, Any]] = Field(
        None, description="Additional error details"
    )


class TokenResponse(BaseModel):
    """JWT token response (for demo/testing)."""
    access_token: str = Field(..., description="JWT access token")
    token_type: str = Field(default="bearer")
    expires_in: int = Field(..., description="Token expiry in seconds")
    message: str = Field(default="Token generated successfully.")
